#!/bin/bash

# NukeLab Platform v2.0 — Unified Management Script
# Usage: ./manage.sh <command> [target] [flags]
#
# Commands are implemented as modules in scripts/manage.d/*.sh

set -euo pipefail

# ─── Shared Helpers ────────────────────────────────────────────────────────
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd)"
cd "$DIR"
source "$DIR/scripts/lib.sh"

# ─── Colors ────────────────────────────────────────────────────────────────
RED=$'\033[0;31m'
GREEN=$'\033[0;32m'
YELLOW=$'\033[1;33m'
BLUE=$'\033[0;34m'
MAGENTA=$'\033[0;35m'
CYAN=$'\033[0;36m'
BOLD=$'\033[1m'
DIM=$'\033[2m'
RESET=$'\033[0m'

# ─── Setup ─────────────────────────────────────────────────────────────────
FRONTEND_PID_FILE="$DIR/.frontend.pid"
STATE_FILE="$DIR/.nukelab-state.sh"
COMPOSE_FILE="$DIR/compose.yml"
DEV_COMPOSE_FILE="$DIR/.nukelab-dev-compose.yml"
COMPOSE_ARGS=(-f "$COMPOSE_FILE")

# ─── Helpers ───────────────────────────────────────────────────────────────
log()   { echo -e "${BLUE}▶${RESET} $*"; }
info()  { echo -e "${CYAN}ℹ${RESET}  $*"; }
ok()    { echo -e "${GREEN}✓${RESET}  $*"; }
warn()  { echo -e "${YELLOW}⚠${RESET}  $*"; }
err()   { echo -e "${RED}✗${RESET}  $*" >&2; }
die()   { err "$*"; exit 1; }
step()  { echo -e "\n${BOLD}${MAGENTA}▸${RESET} ${BOLD}$*${RESET}"; }

# ─── State Persistence ─────────────────────────────────────────────────────
# Remember the compose configuration used at start so stop/status/logs/etc.
# operate on the actual stack even when env vars are no longer exported.

persist_state() {
    local tmp_state="${STATE_FILE}.tmp.$$"
    {
        echo "# NukeLab runtime state — auto-generated by manage.sh"
        echo "# Do not edit by hand; delete this file to force env-based fallback."
        echo "NUKELAB_USE_DEV_MODE=$USE_DEV_MODE"
        echo "NUKELAB_TARGET=$TARGET"
        echo "NUKELAB_PGBOUNCER_ENABLED=${PGBOUNCER_ENABLED:-false}"
        echo "NUKELAB_PROMETHEUS_ENABLED=${PROMETHEUS_ENABLED:-false}"
        echo "NUKELAB_GRAFANA_ENABLED=${GRAFANA_ENABLED:-false}"
        echo "NUKELAB_ALERTMANAGER_ENABLED=${ALERTMANAGER_ENABLED:-false}"
        echo "NUKELAB_TRACING_ENABLED=${TRACING_ENABLED:-false}"
        printf 'NUKELAB_COMPOSE_ARGS=('
        local first=true
        for arg in "${COMPOSE_ARGS[@]}"; do
            if $first; then
                first=false
            else
                printf ' '
            fi
            printf '%q' "$arg"
        done
        printf ')\n'
    } > "$tmp_state"
    mv "$tmp_state" "$STATE_FILE"
}

restore_state() {
    if [ ! -f "$STATE_FILE" ]; then
        return 1
    fi

    # Capture env values and the command-line target before the state file
    # overwrites them. The user-specified target always wins over saved state.
    local _orig_target="$TARGET"
    local _orig_pgbouncer="${PGBOUNCER_ENABLED:-}"
    local _orig_prometheus="${PROMETHEUS_ENABLED:-}"
    local _orig_grafana="${GRAFANA_ENABLED:-}"
    local _orig_alertmanager="${ALERTMANAGER_ENABLED:-}"
    local _orig_tracing="${TRACING_ENABLED:-}"

    # shellcheck source=/dev/null
    source "$STATE_FILE"

    TARGET="$_orig_target"

    USE_DEV_MODE="${NUKELAB_USE_DEV_MODE:-false}"
    PGBOUNCER_ENABLED="${NUKELAB_PGBOUNCER_ENABLED:-false}"
    PROMETHEUS_ENABLED="${NUKELAB_PROMETHEUS_ENABLED:-false}"
    GRAFANA_ENABLED="${NUKELAB_GRAFANA_ENABLED:-false}"
    ALERTMANAGER_ENABLED="${NUKELAB_ALERTMANAGER_ENABLED:-false}"
    TRACING_ENABLED="${NUKELAB_TRACING_ENABLED:-false}"

    if [ ${#NUKELAB_COMPOSE_ARGS[@]} -gt 0 ]; then
        COMPOSE_ARGS=("${NUKELAB_COMPOSE_ARGS[@]}")
    fi

    # Dev compose file is generated by setup_compose_args; recreate it if missing
    # so restored COMPOSE_ARGS remain valid.
    if $USE_DEV_MODE && [ ! -f "$DEV_COMPOSE_FILE" ]; then
        cat > "$DEV_COMPOSE_FILE" << 'EOF'
services:
  backend:
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - ./backend:/app:Z
      - ./resources:/app/resources:ro
  celery-worker:
    volumes:
      - ./backend:/app:Z
      - ./resources:/app/resources:ro
  celery-beat:
    volumes:
      - ./backend:/app:Z
      - ./resources:/app/resources:ro
EOF
    fi

    info "Restoring compose configuration from previous start"

    # Warn when the current environment contradicts the persisted state.
    if [ -n "$_orig_pgbouncer" ] && [ "$_orig_pgbouncer" != "$PGBOUNCER_ENABLED" ]; then
        warn "PGBOUNCER_ENABLED=$PGBOUNCER_ENABLED (from state) overrides current env value $_orig_pgbouncer"
    fi
    if [ -n "$_orig_prometheus" ] && [ "$_orig_prometheus" != "$PROMETHEUS_ENABLED" ]; then
        warn "PROMETHEUS_ENABLED=$PROMETHEUS_ENABLED (from state) overrides current env value $_orig_prometheus"
    fi
    if [ -n "$_orig_grafana" ] && [ "$_orig_grafana" != "$GRAFANA_ENABLED" ]; then
        warn "GRAFANA_ENABLED=$GRAFANA_ENABLED (from state) overrides current env value $_orig_grafana"
    fi
    if [ -n "$_orig_alertmanager" ] && [ "$_orig_alertmanager" != "$ALERTMANAGER_ENABLED" ]; then
        warn "ALERTMANAGER_ENABLED=$ALERTMANAGER_ENABLED (from state) overrides current env value $_orig_alertmanager"
    fi
    if [ -n "$_orig_tracing" ] && [ "$_orig_tracing" != "$TRACING_ENABLED" ]; then
        warn "TRACING_ENABLED=$TRACING_ENABLED (from state) overrides current env value $_orig_tracing"
    fi

    return 0
}

clear_state() {
    rm -f "$STATE_FILE"
}

# ─── Argument Parsing ─────────────────────────────────────────────────────-
CMD=""
TARGET=""
USE_DEV_MODE=false
USE_COVERAGE=false
SHOW_HELP=false
EXTRA_ARGS=()
COMPOSE_OVERLAY_FILES=()

# Per-command options that take a value. These are passed through to command
# parsers so the value is not misinterpreted as a target.
VALUE_OPTIONS=("--tail" "-n" "--timeout" "-t")

parse_args() {
    CMD="${1:-help}"
    shift || true

    # Short-circuit for top-level help.
    case "$CMD" in
        help|--help|-h)
            print_help
            exit 0
            ;;
    esac

    while [[ $# -gt 0 ]]; do
        case "$1" in
            backend|frontend|all)
                TARGET="$1"
                ;;
            --dev|-d)
                USE_DEV_MODE=true
                ;;
            --coverage)
                USE_COVERAGE=true
                ;;
            --overlay|-o)
                shift
                COMPOSE_OVERLAY_FILES+=("$1")
                ;;
            --help|-h)
                SHOW_HELP=true
                ;;
            -*)
                EXTRA_ARGS+=("$1")
                # Preserve the value of known value-taking options, but only
                # while we have not yet fixed the positional target. After the
                # target is known, subsequent tokens are command arguments and
                # must not have their values consumed (e.g. `exec backend ls -t`).
                if [[ -z "$TARGET" ]]; then
                    for _opt in "${VALUE_OPTIONS[@]}"; do
                        if [[ "$1" == "$_opt" && $# -gt 1 ]]; then
                            shift
                            EXTRA_ARGS+=("$1")
                            break
                        fi
                    done
                fi
                ;;
            *)
                if [[ -z "$TARGET" ]]; then
                    TARGET="$1"
                else
                    EXTRA_ARGS+=("$1")
                fi
                ;;
        esac
        shift
    done

    if [[ -z "$TARGET" ]]; then
        TARGET="all"
    fi
}

# ─── Environment ───────────────────────────────────────────────────────────
init_env() {
    # Always load .env as base defaults
    if [ -f .env ]; then
        log "Loading ${BOLD}.env${RESET}"
        load_env_file .env
    fi
    # In dev mode, overlay .env.development on top so dev values win
    if $USE_DEV_MODE && [ -f .env.development ]; then
        log "Loading ${BOLD}.env.development${RESET} (dev overrides)"
        load_env_file .env.development
    elif [ ! -f .env ] && [ -f .env.development ]; then
        log "Loading ${BOLD}.env.development${RESET}"
        load_env_file .env.development
    elif [ ! -f .env ] && [ ! -f .env.development ]; then
        die "No environment file found.\n\n  cp .env.example .env.development"
    fi
}

# ─── Compose Args ─────────────────────────────────────────────────────────-
setup_compose_args() {
    if $USE_DEV_MODE; then
        cat > "$DEV_COMPOSE_FILE" << 'EOF'
services:
  backend:
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - ./backend:/app:Z
      - ./resources:/app/resources:ro
  celery-worker:
    volumes:
      - ./backend:/app:Z
      - ./resources:/app/resources:ro
  celery-beat:
    volumes:
      - ./backend:/app:Z
      - ./resources:/app/resources:ro
EOF
        COMPOSE_ARGS=(-f "$COMPOSE_FILE" -f "$DEV_COMPOSE_FILE")
    else
        rm -f "$DEV_COMPOSE_FILE"
        COMPOSE_ARGS=(-f "$COMPOSE_FILE")
    fi

    # Include overlays from env var (space-separated) and CLI flags
    if [ -n "${COMPOSE_OVERLAYS:-}" ]; then
        read -ra _env_overlays <<< "$COMPOSE_OVERLAYS"
        COMPOSE_OVERLAY_FILES+=("${_env_overlays[@]}")
    fi

    # Auto-inject PgBouncer overlay when explicitly enabled
    if [ "${PGBOUNCER_ENABLED:-false}" = "true" ]; then
        local _pgbouncer_overlay="compose.pgbouncer.yml"
        local _pgbouncer_found=false
        for _o in "${COMPOSE_OVERLAY_FILES[@]}"; do
            if [ "$_o" = "$_pgbouncer_overlay" ]; then
                _pgbouncer_found=true
                break
            fi
        done
        if ! $_pgbouncer_found; then
            COMPOSE_OVERLAY_FILES+=("$_pgbouncer_overlay")
            info "PgBouncer enabled — adding overlay"
        fi

        # Warn if DATABASE_URL also points to PgBouncer (migrations should use direct Postgres)
        if [[ "${DATABASE_URL:-}" =~ pgbouncer ]] || [[ "${DATABASE_URL:-}" =~ :6432 ]]; then
            warn "DATABASE_URL also points to PgBouncer. Migrations should use direct Postgres."
            info "Hint: Keep DATABASE_URL pointed at postgres:5432 for DDL/migrations"
        fi
    fi

    # Auto-inject monitoring overlay when Prometheus or Grafana is enabled.
    # Skip it during backend tests to avoid postgres-exporter consuming
    # connections and competing with the test database.
    if [ "${CMD:-}" != "test" ] && ([[ "${PROMETHEUS_ENABLED:-false}" == "true" ]] || [[ "${GRAFANA_ENABLED:-false}" == "true" ]]); then
        local _monitoring_overlays=("compose.monitoring.yml")
        if [ "${PGBOUNCER_ENABLED:-false}" = "true" ]; then
            _monitoring_overlays+=("compose.monitoring-pgbouncer.yml")
        fi
        for _monitoring_overlay in "${_monitoring_overlays[@]}"; do
            local _monitoring_found=false
            for _o in "${COMPOSE_OVERLAY_FILES[@]}"; do
                if [ "$_o" = "$_monitoring_overlay" ]; then
                    _monitoring_found=true
                    break
                fi
            done
            if ! $_monitoring_found; then
                COMPOSE_OVERLAY_FILES+=("$_monitoring_overlay")
                info "Monitoring enabled via PROMETHEUS_ENABLED/GRAFANA_ENABLED — adding $_monitoring_overlay"
            fi
        done
    fi

    # Auto-inject Alertmanager overlay when enabled
    if [[ "${ALERTMANAGER_ENABLED:-false}" == "true" ]]; then
        local _alertmanager_overlay="compose.alertmanager.yml"
        local _alertmanager_found=false
        for _o in "${COMPOSE_OVERLAY_FILES[@]}"; do
            if [ "$_o" = "$_alertmanager_overlay" ]; then
                _alertmanager_found=true
                break
            fi
        done
        if ! $_alertmanager_found; then
            COMPOSE_OVERLAY_FILES+=("$_alertmanager_overlay")
            info "Alertmanager enabled via ALERTMANAGER_ENABLED — adding $_alertmanager_overlay"
        fi
    fi

    # Auto-inject tracing overlay when enabled
    if [[ "${TRACING_ENABLED:-false}" == "true" ]]; then
        local _tracing_overlay="compose.tracing.yml"
        local _tracing_found=false
        for _o in "${COMPOSE_OVERLAY_FILES[@]}"; do
            if [ "$_o" = "$_tracing_overlay" ]; then
                _tracing_found=true
                break
            fi
        done
        if ! $_tracing_found; then
            COMPOSE_OVERLAY_FILES+=("$_tracing_overlay")
            info "Tracing enabled via TRACING_ENABLED — adding $_tracing_overlay"
        fi
    fi

    # Deduplicate
    declare -A _seen_overlays
    for overlay in "${COMPOSE_OVERLAY_FILES[@]}"; do
        if [ -z "${_seen_overlays[$overlay]:-}" ]; then
            _seen_overlays[$overlay]=1
            if [ -f "$overlay" ]; then
                COMPOSE_ARGS+=(-f "$overlay")
            else
                warn "Compose overlay not found: $overlay"
            fi
        fi
    done
}

# ─── Help ─────────────────────────────────────────────────────────────────-
print_help() {
    cat <<-EOF
${BOLD}${CYAN}NukeLab v2.0${RESET} — Management Script

${BOLD}Usage:${RESET} ./manage.sh <command> [target] [flags]

${BOLD}${MAGENTA}Quick Start:${RESET}
  ${GREEN}start${RESET}      [target] [--dev]         Start services
  ${GREEN}stop${RESET}       [target]                  Stop services
  ${GREEN}restart${RESET}    [target] [--dev]         Restart services
  ${GREEN}status${RESET}                               Show status

${BOLD}Build & Deploy:${RESET}
  ${GREEN}build${RESET}      [target]                  Build containers
  ${GREEN}update${RESET}                               Pull images & rebuild
  ${GREEN}pull${RESET}                                 Pull latest base images

${BOLD}Maintenance:${RESET}
  ${GREEN}clean${RESET}                                Remove dangling images/volumes
  ${GREEN}remove${RESET}     [target]                  Remove containers (keep data)
  ${GREEN}reset${RESET}                                ⚠️ Delete ALL data & containers

${BOLD}Development:${RESET}
  ${GREEN}shell${RESET}      [service]                 Open shell in container
  ${GREEN}exec${RESET}       [service] [command]       Execute command in container
  ${GREEN}logs${RESET}       [service]                 Stream logs
  ${GREEN}install${RESET}    [target]                  Install dependencies

${BOLD}Database:${RESET}
  ${GREEN}db-migrate${RESET}                           Run Alembic migrations
  ${GREEN}db-shell${RESET}                             Open PostgreSQL shell
  ${GREEN}backup${RESET}                               Create database backup
  ${GREEN}restore${RESET}     <file>                   Restore database from backup

${BOLD}Testing:${RESET}
  ${GREEN}test${RESET}       [target] [--coverage]      Run tests
  ${GREEN}e2e${RESET}                                  Run Playwright E2E tests
  ${GREEN}loadtest${RESET}   [profile]                  Run Locust/k6 load tests

${BOLD}Targets:${RESET} ${DIM}(optional, default: all)${RESET}
  backend    Backend services (api, workers, db, redis, traefik)
  frontend   Frontend unit/lint tests
  all        Everything ${DIM}(default)${RESET}

${BOLD}Flags:${RESET}
  --dev, -d      Development mode: backend containers + local Vite dev server
  --coverage     Run tests with coverage report (backend only)
  --overlay, -o  Add a compose overlay file (repeatable)

${BOLD}Examples:${RESET}
  ./manage.sh start                      # Production: all containers
  ./manage.sh start --dev                # Dev: backend containers + Vite
  ./manage.sh stop frontend              # Stop only frontend
  ./manage.sh build backend              # Build backend image only
  ./manage.sh shell backend              # Shell into backend container
  ./manage.sh exec backend python -v     # Run command in backend
  ./manage.sh logs backend -f            # Stream backend logs
  ./manage.sh db-migrate                 # Run migrations
  ./manage.sh backup                     # Backup database
  ./manage.sh restore backups/nukelab_backup_20250607_120000.sql
  ./manage.sh test backend --coverage    # Run backend tests with coverage
  ./manage.sh loadtest baseline          # Run Locust baseline load test
  PGBOUNCER_ENABLED=true ./manage.sh start
                                         # Start with PgBouncer overlay
  ./manage.sh clean                      # Clean up dangling resources

EOF
}

# ─── Command Loader ────────────────────────────────────────────────────────
_dispatch_command() {
    local command="$1"
    local cmd_file="$DIR/scripts/manage.d/${command}.sh"
    if [ ! -f "$cmd_file" ]; then
        die "Command module missing: $cmd_file"
    fi
    source "$cmd_file"

    # Function names cannot contain hyphens, so map db-migrate -> cmd_db_migrate.
    local base_name="${command//-/_}"

    if $SHOW_HELP; then
        local help_func="help_${base_name}"
        if type -t "$help_func" | grep -q function; then
            "$help_func"
        else
            warn "No detailed help available for '$command'."
            print_help
        fi
        exit 0
    fi

    local parse_func="parse_${base_name}_args"
    if type -t "$parse_func" | grep -q function; then
        "$parse_func"
    fi

    "cmd_${base_name}"
}

# ─── Main ─────────────────────────────────────────────────────────────────-
main() {
    parse_args "$@"

    # Command-specific help can be shown without loading env/engine state.
    if $SHOW_HELP; then
        _dispatch_command "$CMD"
        return 0
    fi

    case "$CMD" in
        start|build|update|pull|clean)
            init_env
            detect_engine
            setup_podman_socket
            setup_compose_args
            _dispatch_command "$CMD"
            ;;
        stop|restart|status|logs|remove|reset|shell|exec|db-migrate|db-shell|backup|restore|e2e|loadtest)
            init_env
            detect_engine
            setup_podman_socket
            if ! restore_state; then
                setup_compose_args
            fi
            _dispatch_command "$CMD"
            ;;
        install|test)
            if [ "$TARGET" = "backend" ] || [ "$TARGET" = "all" ]; then
                init_env
                detect_engine
                setup_podman_socket
                if ! restore_state; then
                    setup_compose_args
                fi
            fi
            _dispatch_command "$CMD"
            ;;
        rm)
            CMD="remove"
            init_env
            detect_engine
            setup_podman_socket
            if ! restore_state; then
                setup_compose_args
            fi
            _dispatch_command "remove"
            ;;
        *)
            die "Unknown command: $CMD\nRun './manage.sh help' for usage."
            ;;
    esac
}

main "$@"
