# NukeLab Prometheus alert rules.
# These are loaded by prometheus.yml via rule_files.
# Generated from nukelab.yml.tpl by scripts/generate-prometheus-config.sh.
# Do not edit this file directly; edit the template instead.

groups:
  - name: nukelab-api
    rules:
      - alert: NukeLabHighErrorRate
        expr: |
          sum(rate(nukelab_http_requests_total{status_code=~"5.."}[5m]))
          /
          sum(rate(nukelab_http_requests_total[5m])) > 0.05
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High 5xx error rate on NukeLab API"
          description: "5xx error rate is {{ $value | humanizePercentage }} over the last 5 minutes."

      - alert: NukeLabHighLatency
        # Container lifecycle writes (create/update/delete/start/stop/restart)
        # legitimately take seconds because they wait on the container runtime
        # and readiness probes; exclude them so routine provisioning does not
        # trip the API latency SLI. Create and list share the path label
        # "/api/servers/", so path-only filtering would also drop the busy
        # list endpoint — instead keep all non-server paths plus every GET
        # (the read SLI) and exclude server writes via the method label.
        expr: |
          histogram_quantile(0.99,
            sum(
              rate(nukelab_http_request_duration_seconds_bucket{path!~"/api/servers.*"}[5m])
              or
              rate(nukelab_http_request_duration_seconds_bucket{method="GET"}[5m])
            ) by (le)
          ) > 1.0
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "NukeLab API p99 latency is high"
          description: "p99 latency is {{ $value | humanizeDuration }} over the last 5 minutes."

      - alert: NukeLabTargetDown
        expr: up{job="nukelab-backend"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "NukeLab backend target is down"
          description: "Prometheus has been unable to scrape the NukeLab backend for more than 1 minute."

      - alert: NukeLabContainerStatusLookupFailures
        expr: |
          sum(rate(nukelab_container_status_lookup_failures_total[5m])) by (reason) > 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Container runtime status lookups are failing"
          description: "NukeLab cannot reliably query container status (reason={{ $labels.reason }}). This can cause servers to appear stopped while containers are still running."

  - name: nukelab-infrastructure
    rules:
      - alert: NukeLabPostgresConnectionsHigh
        expr: pg_stat_activity_count / pg_settings_max_connections > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Postgres connection usage is high"
          description: "Postgres is using {{ $value | humanizePercentage }} of max connections."

      - alert: NukeLabRedisMemoryHigh
        expr: |
          (
            redis_memory_max_bytes > 0
            and
            redis_memory_used_bytes / redis_memory_max_bytes > 0.85
          )
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Redis memory usage is high"
          description: "Redis is using {{ $value | humanizePercentage }} of max memory."

      - alert: NukeLabRedisMaxMemoryNotSet
        expr: redis_memory_max_bytes == 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Redis maxmemory is not configured"
          description: "Redis has no maxmemory limit; memory alerts cannot be calculated. Set REDIS_MAXMEMORY in your environment."

      - alert: NukeLabFilesystemSpaceLow
        # node-exporter mounts the host rootfs at ${NODE_EXPORTER_ROOTFS_PATH},
        # so NukeLab data directories (Postgres, Redis, volumes) appear under
        # ${NODE_EXPORTER_ROOTFS_PATH}/... . Keep this in sync with the
        # NODE_EXPORTER_ROOTFS_PATH value in your .env file.
        expr: |
          100 * (
            1
            -
            node_filesystem_avail_bytes{mountpoint=~"${NODE_EXPORTER_ROOTFS_PATH}(/.*)?",fstype!~"tmpfs|ramfs|squashfs|overlay|proc|sysfs|devtmpfs|devfs"}
            /
            node_filesystem_size_bytes{mountpoint=~"${NODE_EXPORTER_ROOTFS_PATH}(/.*)?",fstype!~"tmpfs|ramfs|squashfs|overlay|proc|sysfs|devtmpfs|devfs"}
          ) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "NukeLab host filesystem is more than 80% full"
          description: "Host filesystem {{ $labels.mountpoint }} is {{ $value | humanizePercentage }} full."

      - alert: NukeLabPostgresDatabaseGrowth
        # Predictive alert: if the current growth rate continues, any Postgres
        # database will exceed 80% of the backing host filesystem within 24h.
        expr: |
          (
            predict_linear(pg_database_size_bytes{datname=~".+"}[6h], 24*3600)
            /
            on(instance) group_left
            max by (instance) (
              node_filesystem_size_bytes{mountpoint=~"${NODE_EXPORTER_ROOTFS_PATH}(/.*)?",fstype!~"tmpfs|ramfs|squashfs|overlay|proc|sysfs|devtmpfs|devfs"}
            )
          ) > 0.8
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "Postgres database predicted to exceed 80% of filesystem within 24 hours"
          description: "Database {{ $labels.datname }} on {{ $labels.instance }} is predicted to reach {{ $value | humanizePercentage }} of the host filesystem in 24h."
