providers:
  docker:
    exposedByDefault: false
    network: nukelab-network
  file:
    directory: /etc/traefik/dynamic
    watch: true

entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      trustedIPs:
        - "127.0.0.1/32"
        - "172.16.0.0/12"
  websecure:
    address: ":443"
    forwardedHeaders:
      trustedIPs:
        - "127.0.0.1/32"
        - "172.16.0.0/12"

certificatesResolvers:
  letsencrypt:
    acme:
      email: ${TRAEFIK_ACME_EMAIL:-admin@nukelab.local}
      storage: /letsencrypt/acme.json
      tlsChallenge: {}

log:
  level: INFO

accessLog: {}
