"""add_invitation_expires_at

Revision ID: 1497143a4122
Revises: 8c74e3b26c6c
Create Date: 2026-05-16 09:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1497143a4122'
down_revision = '8c74e3b26c6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace_invitations', sa.Column('expires_at', sa.DateTime(), nullable=True))
    
    # Backfill existing pending invitations with created_at + 7 days
    op.execute("""
        UPDATE workspace_invitations
        SET expires_at = created_at + INTERVAL '7 days'
        WHERE expires_at IS NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace_invitations', 'expires_at')
    # ### end Alembic commands ###
