"""baseline

Revision ID: 8298b4bb8ada
Revises: 
Create Date: 2026-07-02 09:19:00.805903

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8298b4bb8ada'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('cpu_limit', sa.Float(), nullable=True),
    sa.Column('memory_limit', sa.String(length=50), nullable=True),
    sa.Column('disk_limit', sa.String(length=50), nullable=True),
    sa.Column('gpu_limit', sa.Integer(), nullable=True),
    sa.Column('max_servers_per_user', sa.Integer(), nullable=True),
    sa.Column('cost_per_hour', sa.Integer(), nullable=True),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=True),
    sa.Column('allow_scheduling', sa.Boolean(), nullable=True),
    sa.Column('allow_snapshots', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('visible_to_roles', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_server_plans_slug'), 'server_plans', ['slug'], unique=True)
    op.create_table('system_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('cpu_count', sa.Integer(), nullable=True),
    sa.Column('cpu_load_1m', sa.Float(), nullable=True),
    sa.Column('cpu_load_5m', sa.Float(), nullable=True),
    sa.Column('cpu_load_15m', sa.Float(), nullable=True),
    sa.Column('memory_used', sa.BigInteger(), nullable=True),
    sa.Column('memory_total', sa.BigInteger(), nullable=True),
    sa.Column('memory_percent', sa.Float(), nullable=True),
    sa.Column('memory_available', sa.BigInteger(), nullable=True),
    sa.Column('disk_used', sa.BigInteger(), nullable=True),
    sa.Column('disk_total', sa.BigInteger(), nullable=True),
    sa.Column('disk_percent', sa.Float(), nullable=True),
    sa.Column('disk_read_bytes', sa.BigInteger(), nullable=True),
    sa.Column('disk_write_bytes', sa.BigInteger(), nullable=True),
    sa.Column('network_rx_bytes', sa.BigInteger(), nullable=True),
    sa.Column('network_tx_bytes', sa.BigInteger(), nullable=True),
    sa.Column('docker_containers_running', sa.Integer(), nullable=True),
    sa.Column('docker_containers_total', sa.Integer(), nullable=True),
    sa.Column('docker_images_total', sa.Integer(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_system_metrics_collected_at', 'system_metrics', ['collected_at'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('oauth_id', sa.String(length=255), nullable=True),
    sa.Column('nuke_balance', sa.Integer(), nullable=True),
    sa.Column('daily_allowance', sa.Integer(), nullable=True),
    sa.Column('daily_allowance_override', sa.Integer(), nullable=True),
    sa.Column('daily_allowance_override_until', sa.DateTime(), nullable=True),
    sa.Column('last_nuke_reset', sa.DateTime(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('profile_visibility', sa.String(length=20), nullable=False),
    sa.Column('profile', sa.JSON(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('security', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', 'created_at'),
    postgresql_partition_by='RANGE (created_at)'
    )
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_activity_logs_actor_id'), 'activity_logs', ['actor_id'], unique=False)
    op.create_index('ix_activity_logs_created_at', 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_target_type'), 'activity_logs', ['target_type'], unique=False)
    op.create_table('api_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('token_prefix', sa.String(length=16), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_tokens_token_hash'), 'api_tokens', ['token_hash'], unique=False)
    op.create_index(op.f('ix_api_tokens_token_prefix'), 'api_tokens', ['token_prefix'], unique=False)
    op.create_index(op.f('ix_api_tokens_user_id'), 'api_tokens', ['user_id'], unique=False)
    op.create_table('environment_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=False),
    sa.Column('dockerfile', sa.Text(), nullable=True),
    sa.Column('packages', sa.JSON(), nullable=True),
    sa.Column('environment_variables', sa.JSON(), nullable=True),
    sa.Column('volumes', sa.JSON(), nullable=True),
    sa.Column('ports', sa.JSON(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_environment_templates_slug'), 'environment_templates', ['slug'], unique=True)
    op.create_table('login_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_events_timestamp'), 'login_events', ['timestamp'], unique=False)
    op.create_index('ix_login_events_timestamp_method', 'login_events', ['timestamp', 'method'], unique=False)
    op.create_index(op.f('ix_login_events_user_id'), 'login_events', ['user_id'], unique=False)
    op.create_table('maintenance_windows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('notify_offsets', sa.JSON(), nullable=True),
    sa.Column('notified_offsets', sa.JSON(), nullable=True),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('auto_enabled', sa.Boolean(), nullable=True),
    sa.Column('auto_disabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('token_lookup', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_lookup'), 'refresh_tokens', ['token_lookup'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('request_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', 'created_at'),
    postgresql_partition_by='RANGE (created_at)'
    )
    op.create_index(op.f('ix_request_metrics_correlation_id'), 'request_metrics', ['correlation_id'], unique=False)
    op.create_index('ix_request_metrics_created_at', 'request_metrics', ['created_at'], unique=False)
    op.create_index(op.f('ix_request_metrics_path'), 'request_metrics', ['path'], unique=False)
    op.create_index('ix_request_metrics_path_status', 'request_metrics', ['path', 'status_code'], unique=False)
    op.create_index(op.f('ix_request_metrics_status_code'), 'request_metrics', ['status_code'], unique=False)
    op.create_index(op.f('ix_request_metrics_user_id'), 'request_metrics', ['user_id'], unique=False)
    op.create_table('resource_quotas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('max_cpu_total', sa.Float(), nullable=True),
    sa.Column('max_memory_total', sa.String(length=50), nullable=True),
    sa.Column('max_disk_total', sa.String(length=50), nullable=True),
    sa.Column('max_gpu_total', sa.Integer(), nullable=True),
    sa.Column('max_servers_total', sa.Integer(), nullable=True),
    sa.Column('usage_cpu', sa.Float(), nullable=True),
    sa.Column('usage_memory_mb', sa.Integer(), nullable=True),
    sa.Column('usage_disk_mb', sa.Integer(), nullable=True),
    sa.Column('usage_gpu', sa.Integer(), nullable=True),
    sa.Column('usage_servers', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['server_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id'),
    sa.UniqueConstraint('role'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('shared_workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_plan_access',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['server_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'plan_id')
    )
    op.create_table('volume_backups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('volume_name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('backup_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volume_backups_volume_name'), 'volume_backups', ['volume_name'], unique=False)
    op.create_table('volumes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('max_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_mounted_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('server_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('environment_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('server_name', sa.String(length=255), nullable=False),
    sa.Column('requested_cpu', sa.Float(), nullable=True),
    sa.Column('requested_memory', sa.String(length=20), nullable=True),
    sa.Column('requested_disk', sa.String(length=20), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environment_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['server_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('environment_id', sa.UUID(), nullable=True),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('container_id', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('volume_id', sa.UUID(), nullable=True),
    sa.Column('volume_mode', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('allocated_cpu', sa.Float(), nullable=True),
    sa.Column('allocated_memory', sa.String(length=50), nullable=True),
    sa.Column('allocated_disk', sa.String(length=50), nullable=True),
    sa.Column('allocated_gpu', sa.Integer(), nullable=True),
    sa.Column('internal_port', sa.Integer(), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('health_status', sa.String(length=20), nullable=True),
    sa.Column('health_check_config', sa.JSON(), nullable=True),
    sa.Column('last_health_check', sa.DateTime(), nullable=True),
    sa.Column('status_reason', sa.String(length=255), nullable=True),
    sa.Column('stopped_by', sa.UUID(), nullable=True),
    sa.Column('stop_reason', sa.String(length=255), nullable=True),
    sa.Column('total_cost', sa.Integer(), nullable=True),
    sa.Column('last_billed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['volume_id'], ['volumes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspace_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['shared_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_invitation')
    )
    op.create_index(op.f('ix_workspace_invitations_user_id'), 'workspace_invitations', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_invitations_workspace_id'), 'workspace_invitations', ['workspace_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['shared_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'user_id')
    )
    op.create_table('workspace_plan_access',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['server_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['shared_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'plan_id')
    )
    op.create_table('workspace_volumes',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('volume_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('added_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['volume_id'], ['volumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['shared_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'volume_id')
    )
    op.create_table('alert_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('operator', sa.String(length=10), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('notify_admin', sa.Boolean(), nullable=True),
    sa.Column('notify_user', sa.Boolean(), nullable=True),
    sa.Column('email_enabled', sa.Boolean(), nullable=True),
    sa.Column('webhook_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('server_id', sa.UUID(), nullable=True),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'created_at'),
    postgresql_partition_by='RANGE (created_at)'
    )
    op.create_index('ix_credit_transactions_created_at', 'credit_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_credit_transactions_type'), 'credit_transactions', ['type'], unique=False)
    op.create_index(op.f('ix_credit_transactions_user_id'), 'credit_transactions', ['user_id'], unique=False)
    op.create_index('ix_credit_transactions_user_id_created_at', 'credit_transactions', ['user_id', 'created_at'], unique=False)
    op.create_table('daily_server_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('avg_cpu', sa.Float(), nullable=True),
    sa.Column('peak_cpu', sa.Float(), nullable=True),
    sa.Column('avg_memory', sa.Float(), nullable=True),
    sa.Column('peak_memory', sa.Float(), nullable=True),
    sa.Column('avg_network_rx', sa.BigInteger(), nullable=True),
    sa.Column('avg_network_tx', sa.BigInteger(), nullable=True),
    sa.Column('avg_disk_read', sa.BigInteger(), nullable=True),
    sa.Column('avg_disk_write', sa.BigInteger(), nullable=True),
    sa.Column('avg_gpu', sa.Float(), nullable=True),
    sa.Column('peak_gpu', sa.Float(), nullable=True),
    sa.Column('data_points', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'date', name='uq_daily_server_metrics_server_id_date')
    )
    op.create_index('ix_daily_server_metrics_server_id_date', 'daily_server_metrics', ['server_id', 'date'], unique=False)
    op.create_table('health_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('container_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_health_checks_checked_at', 'health_checks', ['checked_at'], unique=False)
    op.create_index('ix_health_checks_server_checked_at', 'health_checks', ['server_id', 'checked_at'], unique=False)
    op.create_table('server_access_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('key_id', sa.String(length=32), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_reason', sa.String(length=255), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=True),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('token_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_server_access_tokens_expires', 'server_access_tokens', ['expires_at'], unique=False)
    op.create_index('idx_server_access_tokens_revoked', 'server_access_tokens', ['revoked_at'], unique=False)
    op.create_index('idx_server_access_tokens_server_user', 'server_access_tokens', ['server_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_server_access_tokens_jti'), 'server_access_tokens', ['jti'], unique=True)
    op.create_table('server_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('container_id', sa.String(length=255), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('cpu_usage_ns', sa.BigInteger(), nullable=True),
    sa.Column('cpu_system_ns', sa.BigInteger(), nullable=True),
    sa.Column('cpu_cores', sa.Integer(), nullable=True),
    sa.Column('memory_used', sa.BigInteger(), nullable=True),
    sa.Column('memory_total', sa.BigInteger(), nullable=True),
    sa.Column('memory_percent', sa.Float(), nullable=True),
    sa.Column('memory_cache', sa.BigInteger(), nullable=True),
    sa.Column('memory_swap_used', sa.BigInteger(), nullable=True),
    sa.Column('disk_read_bytes', sa.BigInteger(), nullable=True),
    sa.Column('disk_write_bytes', sa.BigInteger(), nullable=True),
    sa.Column('disk_read_iops', sa.Integer(), nullable=True),
    sa.Column('disk_write_iops', sa.Integer(), nullable=True),
    sa.Column('network_rx_bytes', sa.BigInteger(), nullable=True),
    sa.Column('network_tx_bytes', sa.BigInteger(), nullable=True),
    sa.Column('network_rx_packets', sa.BigInteger(), nullable=True),
    sa.Column('network_tx_packets', sa.BigInteger(), nullable=True),
    sa.Column('network_rx_errors', sa.Integer(), nullable=True),
    sa.Column('network_tx_errors', sa.Integer(), nullable=True),
    sa.Column('gpu_percent', sa.Float(), nullable=True),
    sa.Column('gpu_memory_used', sa.BigInteger(), nullable=True),
    sa.Column('gpu_memory_total', sa.BigInteger(), nullable=True),
    sa.Column('gpu_temperature', sa.Float(), nullable=True),
    sa.Column('pids', sa.Integer(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'collected_at'),
    postgresql_partition_by='RANGE (collected_at)'
    )
    op.create_index('ix_server_metrics_collected_at', 'server_metrics', ['collected_at'], unique=False)
    op.create_index('ix_server_metrics_server_id_collected_at', 'server_metrics', ['server_id', 'collected_at'], unique=False)
    op.create_table('server_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('server_volumes',
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('volume_id', sa.UUID(), nullable=False),
    sa.Column('mount_path', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['volume_id'], ['volumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('server_id', 'volume_id')
    )
    op.create_table('alert_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('server_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('admin_notified', sa.Boolean(), nullable=True),
    sa.Column('user_notified', sa.Boolean(), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=True),
    sa.Column('webhook_sent', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_value', sa.Float(), nullable=True),
    sa.Column('fired_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_history_created_at', 'alert_history', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alert_history_created_at', table_name='alert_history')
    op.drop_table('alert_history')
    op.drop_table('server_volumes')
    op.drop_table('server_schedules')
    op.drop_index('ix_server_metrics_server_id_collected_at', table_name='server_metrics')
    op.drop_index('ix_server_metrics_collected_at', table_name='server_metrics')
    op.drop_table('server_metrics')
    op.drop_index(op.f('ix_server_access_tokens_jti'), table_name='server_access_tokens')
    op.drop_index('idx_server_access_tokens_server_user', table_name='server_access_tokens')
    op.drop_index('idx_server_access_tokens_revoked', table_name='server_access_tokens')
    op.drop_index('idx_server_access_tokens_expires', table_name='server_access_tokens')
    op.drop_table('server_access_tokens')
    op.drop_index('ix_health_checks_server_checked_at', table_name='health_checks')
    op.drop_index('ix_health_checks_checked_at', table_name='health_checks')
    op.drop_table('health_checks')
    op.drop_index('ix_daily_server_metrics_server_id_date', table_name='daily_server_metrics')
    op.drop_table('daily_server_metrics')
    op.drop_index('ix_credit_transactions_user_id_created_at', table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_user_id'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_type'), table_name='credit_transactions')
    op.drop_index('ix_credit_transactions_created_at', table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_table('alert_rules')
    op.drop_table('workspace_volumes')
    op.drop_table('workspace_plan_access')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_workspace_invitations_workspace_id'), table_name='workspace_invitations')
    op.drop_index(op.f('ix_workspace_invitations_user_id'), table_name='workspace_invitations')
    op.drop_table('workspace_invitations')
    op.drop_table('servers')
    op.drop_table('server_queue')
    op.drop_table('volumes')
    op.drop_index(op.f('ix_volume_backups_volume_name'), table_name='volume_backups')
    op.drop_table('volume_backups')
    op.drop_table('user_plan_access')
    op.drop_table('shared_workspaces')
    op.drop_table('resource_quotas')
    op.drop_index(op.f('ix_request_metrics_user_id'), table_name='request_metrics')
    op.drop_index(op.f('ix_request_metrics_status_code'), table_name='request_metrics')
    op.drop_index('ix_request_metrics_path_status', table_name='request_metrics')
    op.drop_index(op.f('ix_request_metrics_path'), table_name='request_metrics')
    op.drop_index('ix_request_metrics_created_at', table_name='request_metrics')
    op.drop_index(op.f('ix_request_metrics_correlation_id'), table_name='request_metrics')
    op.drop_table('request_metrics')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_lookup'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('maintenance_windows')
    op.drop_index(op.f('ix_login_events_user_id'), table_name='login_events')
    op.drop_index('ix_login_events_timestamp_method', table_name='login_events')
    op.drop_index(op.f('ix_login_events_timestamp'), table_name='login_events')
    op.drop_table('login_events')
    op.drop_index(op.f('ix_environment_templates_slug'), table_name='environment_templates')
    op.drop_table('environment_templates')
    op.drop_index(op.f('ix_api_tokens_user_id'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_token_prefix'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_token_hash'), table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_index(op.f('ix_activity_logs_target_type'), table_name='activity_logs')
    op.drop_index('ix_activity_logs_created_at', table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_actor_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_index('ix_system_metrics_collected_at', table_name='system_metrics')
    op.drop_table('system_metrics')
    op.drop_index(op.f('ix_server_plans_slug'), table_name='server_plans')
    op.drop_table('server_plans')
    # ### end Alembic commands ###
