"""baseline

Revision ID: 89045cede7fe
Revises: 
Create Date: 2026-05-11 19:32:44.824709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89045cede7fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
