"""add_user_and_workspace_plan_access

Revision ID: 953bf4cd75cd
Revises: 4aa05fa3038f
Create Date: 2026-05-21 11:59:47.592575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '953bf4cd75cd'
down_revision = '4aa05fa3038f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_plan_access',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('plan_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('granted_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['server_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'plan_id')
    )
    op.create_index('ix_user_plan_access_plan_id', 'user_plan_access', ['plan_id'], unique=False)
    op.create_index('ix_user_plan_access_user_id', 'user_plan_access', ['user_id'], unique=False)

    op.create_table('workspace_plan_access',
    sa.Column('workspace_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('plan_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('granted_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['server_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['shared_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'plan_id')
    )
    op.create_index('ix_workspace_plan_access_plan_id', 'workspace_plan_access', ['plan_id'], unique=False)
    op.create_index('ix_workspace_plan_access_workspace_id', 'workspace_plan_access', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workspace_plan_access_workspace_id', table_name='workspace_plan_access')
    op.drop_index('ix_workspace_plan_access_plan_id', table_name='workspace_plan_access')
    op.drop_table('workspace_plan_access')
    op.drop_index('ix_user_plan_access_user_id', table_name='user_plan_access')
    op.drop_index('ix_user_plan_access_plan_id', table_name='user_plan_access')
    op.drop_table('user_plan_access')
    # ### end Alembic commands ###
