"""add_profile_visibility_to_users

Revision ID: a1105d874a5a
Revises: 89045cede7fe
Create Date: 2026-05-16 06:35:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1105d874a5a'
down_revision = '89045cede7fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_visibility', sa.String(length=20), nullable=False, server_default='private'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_visibility')
    # ### end Alembic commands ###
