/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolumesRouteImport } from './routes/volumes'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServersRouteImport } from './routes/servers'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as NetworksRouteImport } from './routes/networks'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImagesRouteImport } from './routes/images'
import { Route as EnvironmentsRouteImport } from './routes/environments'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServersServerIdIndexRouteImport } from './routes/servers/$serverId/index'
import { Route as UserUsernameServerNameRouteImport } from './routes/user.$username.$serverName'
import { Route as ServersServerIdMetricsRouteImport } from './routes/servers/$serverId/metrics'

const VolumesRoute = VolumesRouteImport.update({
  id: '/volumes',
  path: '/volumes',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersRoute = ServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworksRoute = NetworksRouteImport.update({
  id: '/networks',
  path: '/networks',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesRoute = ImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentsRoute = EnvironmentsRouteImport.update({
  id: '/environments',
  path: '/environments',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersServerIdIndexRoute = ServersServerIdIndexRouteImport.update({
  id: '/$serverId/',
  path: '/$serverId/',
  getParentRoute: () => ServersRoute,
} as any)
const UserUsernameServerNameRoute = UserUsernameServerNameRouteImport.update({
  id: '/user/$username/$serverName',
  path: '/user/$username/$serverName',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersServerIdMetricsRoute = ServersServerIdMetricsRouteImport.update({
  id: '/$serverId/metrics',
  path: '/$serverId/metrics',
  getParentRoute: () => ServersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/environments': typeof EnvironmentsRoute
  '/images': typeof ImagesRoute
  '/login': typeof LoginRoute
  '/networks': typeof NetworksRoute
  '/plans': typeof PlansRoute
  '/servers': typeof ServersRouteWithChildren
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/volumes': typeof VolumesRoute
  '/servers/$serverId/metrics': typeof ServersServerIdMetricsRoute
  '/user/$username/$serverName': typeof UserUsernameServerNameRoute
  '/servers/$serverId/': typeof ServersServerIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/environments': typeof EnvironmentsRoute
  '/images': typeof ImagesRoute
  '/login': typeof LoginRoute
  '/networks': typeof NetworksRoute
  '/plans': typeof PlansRoute
  '/servers': typeof ServersRouteWithChildren
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/volumes': typeof VolumesRoute
  '/servers/$serverId/metrics': typeof ServersServerIdMetricsRoute
  '/user/$username/$serverName': typeof UserUsernameServerNameRoute
  '/servers/$serverId': typeof ServersServerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/environments': typeof EnvironmentsRoute
  '/images': typeof ImagesRoute
  '/login': typeof LoginRoute
  '/networks': typeof NetworksRoute
  '/plans': typeof PlansRoute
  '/servers': typeof ServersRouteWithChildren
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/volumes': typeof VolumesRoute
  '/servers/$serverId/metrics': typeof ServersServerIdMetricsRoute
  '/user/$username/$serverName': typeof UserUsernameServerNameRoute
  '/servers/$serverId/': typeof ServersServerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-logs'
    | '/environments'
    | '/images'
    | '/login'
    | '/networks'
    | '/plans'
    | '/servers'
    | '/settings'
    | '/users'
    | '/volumes'
    | '/servers/$serverId/metrics'
    | '/user/$username/$serverName'
    | '/servers/$serverId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-logs'
    | '/environments'
    | '/images'
    | '/login'
    | '/networks'
    | '/plans'
    | '/servers'
    | '/settings'
    | '/users'
    | '/volumes'
    | '/servers/$serverId/metrics'
    | '/user/$username/$serverName'
    | '/servers/$serverId'
  id:
    | '__root__'
    | '/'
    | '/audit-logs'
    | '/environments'
    | '/images'
    | '/login'
    | '/networks'
    | '/plans'
    | '/servers'
    | '/settings'
    | '/users'
    | '/volumes'
    | '/servers/$serverId/metrics'
    | '/user/$username/$serverName'
    | '/servers/$serverId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditLogsRoute: typeof AuditLogsRoute
  EnvironmentsRoute: typeof EnvironmentsRoute
  ImagesRoute: typeof ImagesRoute
  LoginRoute: typeof LoginRoute
  NetworksRoute: typeof NetworksRoute
  PlansRoute: typeof PlansRoute
  ServersRoute: typeof ServersRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
  VolumesRoute: typeof VolumesRoute
  UserUsernameServerNameRoute: typeof UserUsernameServerNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volumes': {
      id: '/volumes'
      path: '/volumes'
      fullPath: '/volumes'
      preLoaderRoute: typeof VolumesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers': {
      id: '/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof ServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/networks': {
      id: '/networks'
      path: '/networks'
      fullPath: '/networks'
      preLoaderRoute: typeof NetworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images': {
      id: '/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof ImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environments': {
      id: '/environments'
      path: '/environments'
      fullPath: '/environments'
      preLoaderRoute: typeof EnvironmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/$serverId/': {
      id: '/servers/$serverId/'
      path: '/$serverId'
      fullPath: '/servers/$serverId/'
      preLoaderRoute: typeof ServersServerIdIndexRouteImport
      parentRoute: typeof ServersRoute
    }
    '/user/$username/$serverName': {
      id: '/user/$username/$serverName'
      path: '/user/$username/$serverName'
      fullPath: '/user/$username/$serverName'
      preLoaderRoute: typeof UserUsernameServerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/$serverId/metrics': {
      id: '/servers/$serverId/metrics'
      path: '/$serverId/metrics'
      fullPath: '/servers/$serverId/metrics'
      preLoaderRoute: typeof ServersServerIdMetricsRouteImport
      parentRoute: typeof ServersRoute
    }
  }
}

interface ServersRouteChildren {
  ServersServerIdMetricsRoute: typeof ServersServerIdMetricsRoute
  ServersServerIdIndexRoute: typeof ServersServerIdIndexRoute
}

const ServersRouteChildren: ServersRouteChildren = {
  ServersServerIdMetricsRoute: ServersServerIdMetricsRoute,
  ServersServerIdIndexRoute: ServersServerIdIndexRoute,
}

const ServersRouteWithChildren =
  ServersRoute._addFileChildren(ServersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditLogsRoute: AuditLogsRoute,
  EnvironmentsRoute: EnvironmentsRoute,
  ImagesRoute: ImagesRoute,
  LoginRoute: LoginRoute,
  NetworksRoute: NetworksRoute,
  PlansRoute: PlansRoute,
  ServersRoute: ServersRouteWithChildren,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
  VolumesRoute: VolumesRoute,
  UserUsernameServerNameRoute: UserUsernameServerNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
